//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.31 at 11:41:24 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://jaxb.wk.org/entities")
package org.wk.jaxb.entities;
